"""empty message

Revision ID: 036eb74c8237
Revises: c9db57e4805c
Create Date: 2017-06-28 20:22:04.560041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '036eb74c8237'
down_revision = 'c9db57e4805c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nuccore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nuccore_uid', sa.String(length=50), nullable=True),
    sa.Column('nuccore_link', sa.Text(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nuccore_uid')
    )
    op.drop_column(u'dataset', 'nuccore_uids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'dataset', sa.Column('nuccore_uids', mysql.TEXT(), nullable=True))
    op.drop_table('nuccore')
    # ### end Alembic commands ###
