"""empty message

Revision ID: 0a59f64c68bc
Revises: fa61ceda3a26
Create Date: 2017-06-26 18:38:43.772322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a59f64c68bc'
down_revision = 'fa61ceda3a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'nuccore_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('nuccore_link', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
