"""empty message

Revision ID: 3042244d8e87
Revises: 036eb74c8237
Create Date: 2017-06-28 20:29:58.826974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3042244d8e87'
down_revision = '036eb74c8237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_to_nuccore',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('nuccore_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['nuccore_id'], ['nuccore.id'], )
    )
    op.drop_constraint(u'nuccore_ibfk_1', 'nuccore', type_='foreignkey')
    op.drop_column(u'nuccore', 'dataset_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'nuccore', sa.Column('dataset_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'nuccore_ibfk_1', 'nuccore', 'dataset', ['dataset_id'], ['id'])
    op.drop_table('dataset_to_nuccore')
    # ### end Alembic commands ###
