"""empty message

Revision ID: 356add9f6b39
Revises: ccf6ac1f8856
Create Date: 2017-09-25 17:30:41.581945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356add9f6b39'
down_revision = 'ccf6ac1f8856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovery', sa.Column('discovery_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovery', 'discovery_description')
    # ### end Alembic commands ###
