"""empty message

Revision ID: 406b874c9e9f
Revises: 09893098abbe
Create Date: 2017-09-14 23:53:38.438189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406b874c9e9f'
down_revision = '09893098abbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovery', sa.Column('discovery_title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovery', 'discovery_title')
    # ### end Alembic commands ###
