"""empty message

Revision ID: 5040a994bad1
Revises: 
Create Date: 2017-06-24 20:07:28.050457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5040a994bad1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('betaSignup', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'betaSignup')
    # ### end Alembic commands ###
