"""empty message

Revision ID: 644fed244721
Revises: 23f9adef79ea
Create Date: 2017-07-02 17:47:39.031208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '644fed244721'
down_revision = '23f9adef79ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'library_construction_method',
               existing_type=mysql.TEXT(charset=u'utf8', collation=u'utf8_bin'),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('dataset', 'library_screening_strategy',
               existing_type=mysql.TEXT(charset=u'utf8', collation=u'utf8_bin'),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('dataset', 'library_source',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('dataset', 'library_strategy',
               existing_type=mysql.TEXT(charset=u'utf8', collation=u'utf8_bin'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('dataset', 'sequencing_method',
               existing_type=mysql.TEXT(charset=u'utf8', collation=u'utf8_bin'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('dataset', 'env_biome',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('dataset', 'env_feature',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('dataset', 'env_material',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('dataset', 'env_package',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('dataset', 'geo_loc_name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('dataset', 'instrument_model',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('dataset', 'investigation_type',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('dataset', 'study_type',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'sequencing_method',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(charset=u'utf8', collation=u'utf8_bin'),
               existing_nullable=True)
    op.alter_column('dataset', 'library_strategy',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(charset=u'utf8', collation=u'utf8_bin'),
               existing_nullable=True)
    op.alter_column('dataset', 'library_source',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('dataset', 'library_screening_strategy',
               existing_type=sa.String(length=80),
               type_=mysql.TEXT(charset=u'utf8', collation=u'utf8_bin'),
               existing_nullable=True)
    op.alter_column('dataset', 'library_construction_method',
               existing_type=sa.String(length=20),
               type_=mysql.TEXT(charset=u'utf8', collation=u'utf8_bin'),
               existing_nullable=True)
    op.alter_column('dataset', 'study_type',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('dataset', 'investigation_type',
               existing_type=sa.String(length=80),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('dataset', 'instrument_model',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('dataset', 'geo_loc_name',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('dataset', 'env_package',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('dataset', 'env_material',
               existing_type=sa.String(length=150),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('dataset', 'env_feature',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('dataset', 'env_biome',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
