"""empty message

Revision ID: 833b35158d88
Revises: 5040a994bad1
Create Date: 2017-06-24 20:10:40.828229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833b35158d88'
down_revision = '5040a994bad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('testField', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'testField')
    # ### end Alembic commands ###
