"""empty message

Revision ID: a482d6aceb85
Revises: 01356afcc714
Create Date: 2017-11-09 15:57:26.288532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a482d6aceb85'
down_revision = '01356afcc714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovery', sa.Column('num_datasets', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovery', 'num_datasets')
    # ### end Alembic commands ###
