"""empty message

Revision ID: aa1ce7a80455
Revises: 01b5eeb0b2bf
Create Date: 2017-06-28 11:13:52.438331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1ce7a80455'
down_revision = '01b5eeb0b2bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pubmed_uid', sa.String(length=30), nullable=True),
    sa.Column('pubmed_link', sa.Text(), nullable=True),
    sa.Column('pub_publication_date', sa.DateTime(), nullable=True),
    sa.Column('pub_authors', sa.Text(), nullable=True),
    sa.Column('pub_title', sa.Text(), nullable=True),
    sa.Column('pub_volume', sa.String(length=20), nullable=True),
    sa.Column('pub_issue', sa.String(length=20), nullable=True),
    sa.Column('pub_pages', sa.String(length=30), nullable=True),
    sa.Column('pub_journal', sa.Text(), nullable=True),
    sa.Column('pub_doi', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_to_publication',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset_to_publication')
    op.drop_table('publication')
    # ### end Alembic commands ###
