"""empty message

Revision ID: b472cb98fffd
Revises: 7e206db94cf6
Create Date: 2018-01-04 20:57:19.845298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b472cb98fffd'
down_revision = '7e206db94cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('metaseek_env_package', sa.String(length=50), nullable=True))
    op.add_column('dataset', sa.Column('metaseek_investigation_type', sa.String(length=50), nullable=True))
    op.add_column('dataset', sa.Column('metaseek_investigation_type_P', sa.Float(), nullable=True))
    op.add_column('dataset', sa.Column('metaseek_mixs_specification', sa.String(length=20), nullable=True))
    op.add_column('dataset', sa.Column('metaseek_mixs_specification_P', sa.Float(), nullable=True))
    op.add_column('dataset', sa.Column('metaseek_sequencing_method', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_dataset_metaseek_investigation_type'), 'dataset', ['metaseek_investigation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_metaseek_investigation_type'), table_name='dataset')
    op.drop_column('dataset', 'metaseek_sequencing_method')
    op.drop_column('dataset', 'metaseek_mixs_specification_P')
    op.drop_column('dataset', 'metaseek_mixs_specification')
    op.drop_column('dataset', 'metaseek_investigation_type_P')
    op.drop_column('dataset', 'metaseek_investigation_type')
    op.drop_column('dataset', 'metaseek_env_package')
    # ### end Alembic commands ###
